// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: terra/ustcstaking/v1/ustcstaking.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PositionStatus int32

const (
	PositionStatus_POSITION_STATUS_UNSPECIFIED PositionStatus = 0
	PositionStatus_POSITION_STATUS_ACTIVE      PositionStatus = 1
	PositionStatus_POSITION_STATUS_UNBONDING   PositionStatus = 2
	PositionStatus_POSITION_STATUS_WITHDRAWN   PositionStatus = 3
)

var PositionStatus_name = map[int32]string{
	0: "POSITION_STATUS_UNSPECIFIED",
	1: "POSITION_STATUS_ACTIVE",
	2: "POSITION_STATUS_UNBONDING",
	3: "POSITION_STATUS_WITHDRAWN",
}

var PositionStatus_value = map[string]int32{
	"POSITION_STATUS_UNSPECIFIED": 0,
	"POSITION_STATUS_ACTIVE":      1,
	"POSITION_STATUS_UNBONDING":   2,
	"POSITION_STATUS_WITHDRAWN":   3,
}

func (x PositionStatus) String() string {
	return proto.EnumName(PositionStatus_name, int32(x))
}

func (PositionStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b1d527a7b5bf2f0f, []int{0}
}

type LockTier struct {
	Id         uint32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Duration   *time.Duration              `protobuf:"bytes,2,opt,name=duration,proto3,stdduration" json:"duration,omitempty" yaml:"duration"`
	Multiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=multiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"multiplier" yaml:"multiplier"`
}

func (m *LockTier) Reset()         { *m = LockTier{} }
func (m *LockTier) String() string { return proto.CompactTextString(m) }
func (*LockTier) ProtoMessage()    {}
func (*LockTier) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1d527a7b5bf2f0f, []int{0}
}
func (m *LockTier) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockTier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockTier.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockTier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockTier.Merge(m, src)
}
func (m *LockTier) XXX_Size() int {
	return m.Size()
}
func (m *LockTier) XXX_DiscardUnknown() {
	xxx_messageInfo_LockTier.DiscardUnknown(m)
}

var xxx_messageInfo_LockTier proto.InternalMessageInfo

func (m *LockTier) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LockTier) GetDuration() *time.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

type Position struct {
	Id               uint64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" yaml:"id"`
	Owner            string                      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty" yaml:"owner"`
	Principal        types1.Coin                 `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal" yaml:"principal"`
	Shares           cosmossdk_io_math.Int       `protobuf:"bytes,4,opt,name=shares,proto3,customtype=cosmossdk.io/math.Int" json:"shares" yaml:"shares"`
	LockTierId       uint32                      `protobuf:"varint,5,opt,name=lock_tier_id,json=lockTierId,proto3" json:"lock_tier_id,omitempty" yaml:"lock_tier_id"`
	ShareMultiplier  cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=share_multiplier,json=shareMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"share_multiplier" yaml:"share_multiplier"`
	RewardDebt       cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=reward_debt,json=rewardDebt,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reward_debt" yaml:"reward_debt"`
	UnbondingEndTime *time.Time                  `protobuf:"bytes,8,opt,name=unbonding_end_time,json=unbondingEndTime,proto3,stdtime" json:"unbonding_end_time,omitempty" yaml:"unbonding_end_time"`
	Status           PositionStatus              `protobuf:"varint,9,opt,name=status,proto3,enum=terra.ustcstaking.v1.PositionStatus" json:"status,omitempty" yaml:"status"`
	ClaimableRewards types1.Coin                 `protobuf:"bytes,10,opt,name=claimable_rewards,json=claimableRewards,proto3" json:"claimable_rewards" yaml:"claimable_rewards"`
	LockDuration     *time.Duration              `protobuf:"bytes,11,opt,name=lock_duration,json=lockDuration,proto3,stdduration" json:"lock_duration,omitempty" yaml:"lock_duration"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1d527a7b5bf2f0f, []int{1}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

type RewardState struct {
	RewardIndex cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=reward_index,json=rewardIndex,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reward_index" yaml:"reward_index"`
	TotalShares cosmossdk_io_math.Int       `protobuf:"bytes,2,opt,name=total_shares,json=totalShares,proto3,customtype=cosmossdk.io/math.Int" json:"total_shares" yaml:"total_shares"`
}

func (m *RewardState) Reset()         { *m = RewardState{} }
func (m *RewardState) String() string { return proto.CompactTextString(m) }
func (*RewardState) ProtoMessage()    {}
func (*RewardState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1d527a7b5bf2f0f, []int{2}
}
func (m *RewardState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardState.Merge(m, src)
}
func (m *RewardState) XXX_Size() int {
	return m.Size()
}
func (m *RewardState) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardState.DiscardUnknown(m)
}

var xxx_messageInfo_RewardState proto.InternalMessageInfo

type Params struct {
	BondDenom        string     `protobuf:"bytes,1,opt,name=bond_denom,json=bondDenom,proto3" json:"bond_denom,omitempty" yaml:"bond_denom"`
	LockTiers        []LockTier `protobuf:"bytes,2,rep,name=lock_tiers,json=lockTiers,proto3" json:"lock_tiers" yaml:"lock_tiers"`
	Authority        string     `protobuf:"bytes,3,opt,name=authority,proto3" json:"authority,omitempty" yaml:"authority"`
	FundingAuthority string     `protobuf:"bytes,4,opt,name=funding_authority,json=fundingAuthority,proto3" json:"funding_authority,omitempty" yaml:"funding_authority"`
	Paused           bool       `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty" yaml:"paused"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1d527a7b5bf2f0f, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBondDenom() string {
	if m != nil {
		return m.BondDenom
	}
	return ""
}

func (m *Params) GetLockTiers() []LockTier {
	if m != nil {
		return m.LockTiers
	}
	return nil
}

func (m *Params) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Params) GetFundingAuthority() string {
	if m != nil {
		return m.FundingAuthority
	}
	return ""
}

func (m *Params) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func init() {
	proto.RegisterEnum("terra.ustcstaking.v1.PositionStatus", PositionStatus_name, PositionStatus_value)
	proto.RegisterType((*LockTier)(nil), "terra.ustcstaking.v1.LockTier")
	proto.RegisterType((*Position)(nil), "terra.ustcstaking.v1.Position")
	proto.RegisterType((*RewardState)(nil), "terra.ustcstaking.v1.RewardState")
	proto.RegisterType((*Params)(nil), "terra.ustcstaking.v1.Params")
}

func init() {
	proto.RegisterFile("terra/ustcstaking/v1/ustcstaking.proto", fileDescriptor_b1d527a7b5bf2f0f)
}

var fileDescriptor_b1d527a7b5bf2f0f = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0xa6, 0xa9, 0x6b, 0x8f, 0x93, 0xd6, 0x99, 0xa6, 0x74, 0x93, 0x52, 0x6f, 0x58, 0x21,
	0x64, 0x10, 0xdd, 0x55, 0x42, 0x2e, 0x44, 0x08, 0x29, 0x1b, 0xa7, 0xed, 0xa2, 0xe0, 0x84, 0xb5,
	0x4b, 0x11, 0x42, 0x5a, 0x8d, 0x77, 0x27, 0xf6, 0xc8, 0xeb, 0x1d, 0x6b, 0x67, 0x9c, 0x34, 0xff,
	0x00, 0x89, 0x4b, 0x8f, 0x1c, 0xfb, 0x23, 0xf8, 0x01, 0x1c, 0x7b, 0xac, 0x38, 0x21, 0x0e, 0x06,
	0x92, 0x03, 0x9c, 0x7d, 0xe2, 0x88, 0x76, 0x66, 0x6c, 0x6f, 0xe2, 0x44, 0xc9, 0xcd, 0xf3, 0xde,
	0xfb, 0xde, 0x9b, 0x37, 0xef, 0xfb, 0x9e, 0x17, 0x7c, 0xc4, 0x71, 0x92, 0x20, 0x7b, 0xc0, 0x78,
	0xc0, 0x38, 0xea, 0x92, 0xb8, 0x6d, 0x1f, 0xad, 0x67, 0x8f, 0x56, 0x3f, 0xa1, 0x9c, 0xc2, 0x65,
	0x11, 0x67, 0x65, 0x1d, 0x47, 0xeb, 0xab, 0x95, 0x80, 0xb2, 0x1e, 0x65, 0x76, 0x0b, 0x31, 0x6c,
	0x1f, 0xad, 0xb7, 0x30, 0x47, 0xeb, 0x76, 0x40, 0x49, 0x2c, 0x51, 0xab, 0x2b, 0xd2, 0xef, 0x8b,
	0x93, 0x2d, 0x0f, 0xca, 0x55, 0x69, 0x53, 0xda, 0x8e, 0xb0, 0x2d, 0x4e, 0xad, 0xc1, 0xa1, 0x1d,
	0x0e, 0x12, 0xc4, 0x09, 0x1d, 0x43, 0x8d, 0x8b, 0x7e, 0x4e, 0x7a, 0x98, 0x71, 0xd4, 0xeb, 0xab,
	0x80, 0xe5, 0x36, 0x6d, 0x53, 0x99, 0x38, 0xfd, 0x25, 0xad, 0xe6, 0x3f, 0x1a, 0x28, 0xec, 0xd1,
	0xa0, 0xdb, 0x24, 0x38, 0x81, 0x8f, 0xc1, 0x1c, 0x09, 0x75, 0x6d, 0x4d, 0xab, 0x2e, 0x3a, 0x8b,
	0xa3, 0xa1, 0x51, 0x3c, 0x41, 0xbd, 0x68, 0xcb, 0x24, 0xa1, 0xe9, 0xcd, 0x91, 0x10, 0xd6, 0x41,
	0x61, 0x5c, 0x54, 0x9f, 0x5b, 0xd3, 0xaa, 0xa5, 0x8d, 0x15, 0x4b, 0x56, 0xb5, 0xc6, 0x55, 0xad,
	0x9a, 0x0a, 0x70, 0x1e, 0x8e, 0x86, 0xc6, 0x3d, 0x89, 0x1f, 0x83, 0xcc, 0x9f, 0xff, 0x34, 0x34,
	0x6f, 0x92, 0x03, 0x1e, 0x02, 0xd0, 0x1b, 0x44, 0x9c, 0xf4, 0x23, 0x82, 0x13, 0xfd, 0xd6, 0x9a,
	0x56, 0x2d, 0x3a, 0x4f, 0xdf, 0x0e, 0x8d, 0xdc, 0x1f, 0x43, 0xe3, 0x91, 0x6c, 0x9e, 0x85, 0x5d,
	0x8b, 0x50, 0xbb, 0x87, 0x78, 0xc7, 0xda, 0xc3, 0x6d, 0x14, 0x9c, 0xd4, 0x70, 0x30, 0x1a, 0x1a,
	0x4b, 0x32, 0xf3, 0x14, 0x6e, 0xfe, 0xf6, 0xcb, 0x13, 0xa0, 0x1e, 0xac, 0x86, 0x03, 0x2f, 0x93,
	0x79, 0x6b, 0xfe, 0xdf, 0x37, 0x86, 0x66, 0xfe, 0x7a, 0x07, 0x14, 0x0e, 0x28, 0x23, 0xa2, 0xf4,
	0xb4, 0xd3, 0xf9, 0xcb, 0x3a, 0xfd, 0x12, 0xdc, 0xa6, 0xc7, 0x31, 0x4e, 0x44, 0x9b, 0x45, 0xa7,
	0x3a, 0x1a, 0x1a, 0x0b, 0x32, 0x42, 0x98, 0xd3, 0x62, 0xcb, 0xaa, 0xd8, 0x76, 0x18, 0x26, 0x98,
	0xb1, 0x06, 0x4f, 0x48, 0xdc, 0xf6, 0x24, 0x0c, 0x7e, 0x03, 0x8a, 0xfd, 0x84, 0xc4, 0x01, 0xe9,
	0xa3, 0x48, 0x34, 0x96, 0x3e, 0x95, 0x02, 0xa4, 0xb3, 0xb7, 0xd4, 0xec, 0xad, 0x1d, 0x4a, 0x62,
	0x47, 0x4f, 0x7b, 0x1e, 0x0d, 0x8d, 0xb2, 0x2c, 0x31, 0x41, 0x9a, 0xde, 0x34, 0x0b, 0x6c, 0x82,
	0x3c, 0xeb, 0xa0, 0x04, 0x33, 0x7d, 0x5e, 0xdc, 0xe9, 0x0b, 0xf5, 0x50, 0x0f, 0x66, 0x1f, 0xca,
	0x8d, 0xf9, 0x68, 0x68, 0x2c, 0xca, 0x6c, 0x12, 0x94, 0x7d, 0x1e, 0x37, 0xe6, 0x9e, 0xca, 0x05,
	0x3f, 0x07, 0x0b, 0x11, 0x0d, 0xba, 0x3e, 0x27, 0x38, 0xf1, 0x49, 0xa8, 0xdf, 0x16, 0xb3, 0x4f,
	0x67, 0x77, 0x5f, 0xc2, 0xb3, 0x5e, 0xd3, 0x03, 0x91, 0xa2, 0x8a, 0x1b, 0xc2, 0x63, 0x50, 0x16,
	0x49, 0xfc, 0xcc, 0x0c, 0xf3, 0xe2, 0x6a, 0x7b, 0x37, 0x9b, 0xe1, 0xc3, 0xcc, 0x05, 0xfd, 0xab,
	0x27, 0x79, 0x4f, 0x04, 0x7c, 0x3d, 0xf1, 0xc3, 0x0e, 0x28, 0x25, 0xf8, 0x18, 0x25, 0xa1, 0x1f,
	0xe2, 0x16, 0xd7, 0xef, 0x88, 0x9a, 0xcf, 0x6e, 0x56, 0x13, 0xca, 0x9a, 0x19, 0xfc, 0x0c, 0x71,
	0xa4, 0xaf, 0x86, 0x5b, 0x1c, 0x76, 0x01, 0x1c, 0xc4, 0x2d, 0x1a, 0x87, 0x24, 0x6e, 0xfb, 0x38,
	0x0e, 0xfd, 0x54, 0x53, 0x7a, 0x41, 0xcc, 0x73, 0x75, 0x86, 0xfa, 0xcd, 0xb1, 0xe0, 0x9c, 0x0f,
	0x46, 0x43, 0x63, 0x45, 0x56, 0x9a, 0xc5, 0x9b, 0xaf, 0x53, 0x15, 0x94, 0x27, 0x8e, 0xdd, 0x38,
	0x4c, 0x91, 0x70, 0x1f, 0xe4, 0x19, 0x47, 0x7c, 0xc0, 0xf4, 0xe2, 0x9a, 0x56, 0xbd, 0xbb, 0xf1,
	0xa1, 0x75, 0xd9, 0x0a, 0xb1, 0xc6, 0x14, 0x6e, 0x88, 0x58, 0x67, 0x29, 0x33, 0x69, 0x61, 0x31,
	0x3d, 0x95, 0x06, 0x76, 0xc0, 0x52, 0x10, 0x21, 0xd2, 0x43, 0xad, 0x08, 0xfb, 0xb2, 0x2b, 0xa6,
	0x83, 0xeb, 0xc8, 0xb8, 0xa6, 0xc8, 0xa8, 0xcb, 0xa4, 0x33, 0x19, 0x4c, 0xaf, 0x3c, 0xb1, 0x79,
	0xd2, 0x04, 0x7f, 0x00, 0x8b, 0x82, 0x27, 0x93, 0xed, 0x50, 0xba, 0x6e, 0x3b, 0xbc, 0x3f, 0x1a,
	0x1a, 0xcb, 0x19, 0x86, 0x9d, 0x5f, 0x11, 0x82, 0x93, 0xe3, 0xd8, 0xad, 0xc2, 0x8f, 0x6f, 0x8c,
	0x9c, 0x90, 0xf0, 0xdf, 0x1a, 0x28, 0xc9, 0x9a, 0x69, 0xf7, 0x18, 0x76, 0xc1, 0x82, 0x9a, 0x24,
	0x89, 0x43, 0xfc, 0x4a, 0xe8, 0xb9, 0xe8, 0x3c, 0xbf, 0x19, 0x15, 0xee, 0x9f, 0xa3, 0x82, 0x48,
	0x70, 0x91, 0x0b, 0x8a, 0x67, 0x6e, 0xea, 0x83, 0x18, 0x2c, 0x70, 0xca, 0x51, 0xe4, 0x2b, 0x19,
	0xca, 0xd5, 0xe0, 0x5c, 0x27, 0x43, 0x55, 0x26, 0x0b, 0xbd, 0x28, 0xc6, 0x92, 0x70, 0x36, 0xa4,
	0xef, 0xbf, 0x39, 0x90, 0x3f, 0x40, 0x09, 0xea, 0x31, 0xb8, 0x09, 0x40, 0xca, 0x11, 0x3f, 0xc4,
	0x31, 0xed, 0xa9, 0xe6, 0x1e, 0x4c, 0x97, 0xdf, 0xd4, 0x67, 0x7a, 0xc5, 0xf4, 0x50, 0x4b, 0x7f,
	0xc3, 0xef, 0x00, 0x98, 0x88, 0x36, 0xbd, 0xe5, 0xad, 0x6a, 0x69, 0xa3, 0x72, 0x39, 0x97, 0xc6,
	0x8b, 0xdf, 0x59, 0x51, 0x43, 0x5f, 0xba, 0x20, 0x7a, 0x66, 0x7a, 0xc5, 0xb1, 0xe4, 0x19, 0xfc,
	0x0a, 0x14, 0xd1, 0x80, 0x77, 0x68, 0x42, 0xf8, 0x89, 0x5a, 0xd7, 0x9f, 0x4e, 0xd7, 0xd6, 0xc4,
	0x75, 0xf5, 0x76, 0x9c, 0xc2, 0x21, 0x02, 0x4b, 0x87, 0x03, 0x29, 0x8c, 0x69, 0x4e, 0xb9, 0xd9,
	0x36, 0xa7, 0xec, 0x9b, 0x09, 0xb9, 0x3a, 0x77, 0x59, 0xc5, 0x6e, 0x4f, 0x4a, 0x7c, 0x0c, 0xf2,
	0x7d, 0x34, 0x60, 0x58, 0x6e, 0xb5, 0x42, 0x56, 0x2a, 0xd2, 0x6e, 0x7a, 0x2a, 0x40, 0xfe, 0x43,
	0x7c, 0xf2, 0x93, 0x06, 0xee, 0x9e, 0x97, 0x17, 0x34, 0xc0, 0xa3, 0x83, 0xfd, 0x86, 0xdb, 0x74,
	0xf7, 0xeb, 0x7e, 0xa3, 0xb9, 0xdd, 0x7c, 0xd1, 0xf0, 0x5f, 0xd4, 0x1b, 0x07, 0xbb, 0x3b, 0xee,
	0x53, 0x77, 0xb7, 0x56, 0xce, 0xc1, 0x55, 0xf0, 0xde, 0xc5, 0x80, 0xed, 0x9d, 0xa6, 0xfb, 0xed,
	0x6e, 0x59, 0x83, 0x8f, 0xc1, 0xca, 0x2c, 0xd8, 0xd9, 0xaf, 0xd7, 0xdc, 0xfa, 0xb3, 0xf2, 0xdc,
	0x65, 0xee, 0x97, 0x6e, 0xf3, 0x79, 0xcd, 0xdb, 0x7e, 0x59, 0x2f, 0xdf, 0x72, 0xea, 0x6f, 0x4f,
	0x2b, 0xda, 0xbb, 0xd3, 0x8a, 0xf6, 0xd7, 0x69, 0x45, 0x7b, 0x7d, 0x56, 0xc9, 0xbd, 0x3b, 0xab,
	0xe4, 0x7e, 0x3f, 0xab, 0xe4, 0xbe, 0xdf, 0x6c, 0x13, 0xde, 0x19, 0xb4, 0xac, 0x80, 0xf6, 0xec,
	0x20, 0x42, 0x8c, 0x91, 0xe0, 0x89, 0xfc, 0x2c, 0x09, 0x68, 0x82, 0xed, 0xa3, 0x4d, 0xfb, 0xd5,
	0xb9, 0x0f, 0x14, 0x7e, 0xd2, 0xc7, 0xac, 0x95, 0x17, 0x2a, 0xfc, 0xec, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x76, 0xc5, 0x0c, 0x0a, 0xc2, 0x08, 0x00, 0x00,
}

func (this *LockTier) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LockTier)
	if !ok {
		that2, ok := that.(LockTier)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Duration != nil && that1.Duration != nil {
		if *this.Duration != *that1.Duration {
			return false
		}
	} else if this.Duration != nil {
		return false
	} else if that1.Duration != nil {
		return false
	}
	if !this.Multiplier.Equal(that1.Multiplier) {
		return false
	}
	return true
}
func (this *Position) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Position)
	if !ok {
		that2, ok := that.(Position)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Owner != that1.Owner {
		return false
	}
	if !this.Principal.Equal(&that1.Principal) {
		return false
	}
	if !this.Shares.Equal(that1.Shares) {
		return false
	}
	if this.LockTierId != that1.LockTierId {
		return false
	}
	if !this.ShareMultiplier.Equal(that1.ShareMultiplier) {
		return false
	}
	if !this.RewardDebt.Equal(that1.RewardDebt) {
		return false
	}
	if that1.UnbondingEndTime == nil {
		if this.UnbondingEndTime != nil {
			return false
		}
	} else if !this.UnbondingEndTime.Equal(*that1.UnbondingEndTime) {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if !this.ClaimableRewards.Equal(&that1.ClaimableRewards) {
		return false
	}
	if this.LockDuration != nil && that1.LockDuration != nil {
		if *this.LockDuration != *that1.LockDuration {
			return false
		}
	} else if this.LockDuration != nil {
		return false
	} else if that1.LockDuration != nil {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.BondDenom != that1.BondDenom {
		return false
	}
	if len(this.LockTiers) != len(that1.LockTiers) {
		return false
	}
	for i := range this.LockTiers {
		if !this.LockTiers[i].Equal(&that1.LockTiers[i]) {
			return false
		}
	}
	if this.Authority != that1.Authority {
		return false
	}
	if this.FundingAuthority != that1.FundingAuthority {
		return false
	}
	if this.Paused != that1.Paused {
		return false
	}
	return true
}
func (m *LockTier) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockTier) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockTier) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Multiplier.Size()
		i -= size
		if _, err := m.Multiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Duration != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(*m.Duration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.Duration):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintUstcstaking(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintUstcstaking(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LockDuration != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(*m.LockDuration, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.LockDuration):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintUstcstaking(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x5a
	}
	{
		size, err := m.ClaimableRewards.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.Status != 0 {
		i = encodeVarintUstcstaking(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	if m.UnbondingEndTime != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.UnbondingEndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UnbondingEndTime):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintUstcstaking(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x42
	}
	{
		size := m.RewardDebt.Size()
		i -= size
		if _, err := m.RewardDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ShareMultiplier.Size()
		i -= size
		if _, err := m.ShareMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.LockTierId != 0 {
		i = encodeVarintUstcstaking(dAtA, i, uint64(m.LockTierId))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.Principal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintUstcstaking(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintUstcstaking(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RewardState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalShares.Size()
		i -= size
		if _, err := m.TotalShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.RewardIndex.Size()
		i -= size
		if _, err := m.RewardIndex.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintUstcstaking(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.FundingAuthority) > 0 {
		i -= len(m.FundingAuthority)
		copy(dAtA[i:], m.FundingAuthority)
		i = encodeVarintUstcstaking(dAtA, i, uint64(len(m.FundingAuthority)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintUstcstaking(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.LockTiers) > 0 {
		for iNdEx := len(m.LockTiers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LockTiers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUstcstaking(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.BondDenom) > 0 {
		i -= len(m.BondDenom)
		copy(dAtA[i:], m.BondDenom)
		i = encodeVarintUstcstaking(dAtA, i, uint64(len(m.BondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUstcstaking(dAtA []byte, offset int, v uint64) int {
	offset -= sovUstcstaking(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LockTier) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovUstcstaking(uint64(m.Id))
	}
	if m.Duration != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.Duration)
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	l = m.Multiplier.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	return n
}

func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovUstcstaking(uint64(m.Id))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	l = m.Principal.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	l = m.Shares.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	if m.LockTierId != 0 {
		n += 1 + sovUstcstaking(uint64(m.LockTierId))
	}
	l = m.ShareMultiplier.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	l = m.RewardDebt.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	if m.UnbondingEndTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.UnbondingEndTime)
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovUstcstaking(uint64(m.Status))
	}
	l = m.ClaimableRewards.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	if m.LockDuration != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.LockDuration)
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	return n
}

func (m *RewardState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RewardIndex.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	l = m.TotalShares.Size()
	n += 1 + l + sovUstcstaking(uint64(l))
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BondDenom)
	if l > 0 {
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	if len(m.LockTiers) > 0 {
		for _, e := range m.LockTiers {
			l = e.Size()
			n += 1 + l + sovUstcstaking(uint64(l))
		}
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	l = len(m.FundingAuthority)
	if l > 0 {
		n += 1 + l + sovUstcstaking(uint64(l))
	}
	if m.Paused {
		n += 2
	}
	return n
}

func sovUstcstaking(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUstcstaking(x uint64) (n int) {
	return sovUstcstaking(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LockTier) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUstcstaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LockTier: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LockTier: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Duration == nil {
				m.Duration = new(time.Duration)
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Multiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Multiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUstcstaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUstcstaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Principal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Principal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockTierId", wireType)
			}
			m.LockTierId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockTierId |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingEndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UnbondingEndTime == nil {
				m.UnbondingEndTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.UnbondingEndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PositionStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimableRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClaimableRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockDuration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LockDuration == nil {
				m.LockDuration = new(time.Duration)
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(m.LockDuration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUstcstaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUstcstaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardIndex.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUstcstaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUstcstaking
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockTiers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LockTiers = append(m.LockTiers, LockTier{})
			if err := m.LockTiers[len(m.LockTiers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUstcstaking
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FundingAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipUstcstaking(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUstcstaking
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUstcstaking(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUstcstaking
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUstcstaking
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUstcstaking
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUstcstaking
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUstcstaking
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUstcstaking        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUstcstaking          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUstcstaking = fmt.Errorf("proto: unexpected end of group")
)
